const suggestions = [
  { label: "AUD" },
  { label: "BGN" },
  { label: "BRL" },
  { label: "CAD" },
  { label: "CHF" },
  { label: "CNY" },
  { label: "CZK" },
  { label: "DKK" },
  { label: "GBP" },
  { label: "HKD" },
  { label: "HRK" },
  { label: "HUF" },
  { label: "IDR" },
  { label: "ILS" },
  { label: "INR" },
  { label: "ISK" },
  { label: "JPY" },
  { label: "KRW" },
  { label: "MXN" },
  { label: "MYR" },
  { label: "NOK" },
  { label: "NZD" },
  { label: "PHP" },
  { label: "PLN" },
  { label: "RON" },
  { label: "RUB" },
  { label: "SEK" },
  { label: "SGD" },
  { label: "THB" },
  { label: "TRY" },
  { label: "USD" },
  { label: "ZAR" },
];

export default suggestions;